version: '3.1'

services:
  dvwa:
    image: vulnerables/web-dvwa
    container_name: dvwa
    ports:
      - "8080:80"
    environment:
      MYSQL_USER: dvwa
      MYSQL_PASSWORD: p@ssw0rd
      MYSQL_DATABASE: dvwa
      MYSQL_HOST: db
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: dvwa-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: dvwa
      MYSQL_USER: dvwa
      MYSQL_PASSWORD: p@ssw0rd
    volumes:
      - dvwa-mysql:/var/lib/mysql

volumes:
  dvwa-mysql:

